/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiculesRouteImport } from './routes/vehicules'
import { Route as ServicesPrivesRouteImport } from './routes/services-prives'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as LogementsRouteImport } from './routes/logements'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as BonnesAdressesRouteImport } from './routes/bonnes-adresses'
import { Route as ActivitesTerrestresRouteImport } from './routes/activites-terrestres'
import { Route as ActivitesAquatiquesRouteImport } from './routes/activites-aquatiques'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonCompteIndexRouteImport } from './routes/mon-compte/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ReservationSlugRouteImport } from './routes/reservation.$slug'
import { Route as OffresSlugRouteImport } from './routes/offres.$slug'
import { Route as MonCompteReservationsRouteImport } from './routes/mon-compte/reservations'
import { Route as MonCompteProfilRouteImport } from './routes/mon-compte/profil'
import { Route as MonComptePaiementsRouteImport } from './routes/mon-compte/paiements'
import { Route as MonCompteDocumentsRouteImport } from './routes/mon-compte/documents'
import { Route as AdminReservationsRouteImport } from './routes/admin/reservations'
import { Route as AdminParametresRouteImport } from './routes/admin/parametres'
import { Route as AdminPaiementsRouteImport } from './routes/admin/paiements'
import { Route as AdminPacksRouteImport } from './routes/admin/packs'
import { Route as AdminOffresRouteImport } from './routes/admin/offres'
import { Route as AdminFournisseursRouteImport } from './routes/admin/fournisseurs'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminDisponibilitesRouteImport } from './routes/admin/disponibilites'
import { Route as AdminConcoursRouteImport } from './routes/admin/concours'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'

const VehiculesRoute = VehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPrivesRoute = ServicesPrivesRouteImport.update({
  id: '/services-prives',
  path: '/services-prives',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const LogementsRoute = LogementsRouteImport.update({
  id: '/logements',
  path: '/logements',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BonnesAdressesRoute = BonnesAdressesRouteImport.update({
  id: '/bonnes-adresses',
  path: '/bonnes-adresses',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesTerrestresRoute = ActivitesTerrestresRouteImport.update({
  id: '/activites-terrestres',
  path: '/activites-terrestres',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesAquatiquesRoute = ActivitesAquatiquesRouteImport.update({
  id: '/activites-aquatiques',
  path: '/activites-aquatiques',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCompteIndexRoute = MonCompteIndexRouteImport.update({
  id: '/mon-compte/',
  path: '/mon-compte/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationSlugRoute = ReservationSlugRouteImport.update({
  id: '/reservation/$slug',
  path: '/reservation/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresSlugRoute = OffresSlugRouteImport.update({
  id: '/offres/$slug',
  path: '/offres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCompteReservationsRoute = MonCompteReservationsRouteImport.update({
  id: '/mon-compte/reservations',
  path: '/mon-compte/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCompteProfilRoute = MonCompteProfilRouteImport.update({
  id: '/mon-compte/profil',
  path: '/mon-compte/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const MonComptePaiementsRoute = MonComptePaiementsRouteImport.update({
  id: '/mon-compte/paiements',
  path: '/mon-compte/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCompteDocumentsRoute = MonCompteDocumentsRouteImport.update({
  id: '/mon-compte/documents',
  path: '/mon-compte/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/admin/reservations',
  path: '/admin/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/admin/parametres',
  path: '/admin/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/admin/paiements',
  path: '/admin/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPacksRoute = AdminPacksRouteImport.update({
  id: '/admin/packs',
  path: '/admin/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOffresRoute = AdminOffresRouteImport.update({
  id: '/admin/offres',
  path: '/admin/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFournisseursRoute = AdminFournisseursRouteImport.update({
  id: '/admin/fournisseurs',
  path: '/admin/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisponibilitesRoute = AdminDisponibilitesRouteImport.update({
  id: '/admin/disponibilites',
  path: '/admin/disponibilites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConcoursRoute = AdminConcoursRouteImport.update({
  id: '/admin/concours',
  path: '/admin/concours',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activites-aquatiques': typeof ActivitesAquatiquesRoute
  '/activites-terrestres': typeof ActivitesTerrestresRoute
  '/bonnes-adresses': typeof BonnesAdressesRoute
  '/confirmation': typeof ConfirmationRoute
  '/logements': typeof LogementsRoute
  '/packs': typeof PacksRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/services-prives': typeof ServicesPrivesRoute
  '/vehicules': typeof VehiculesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/concours': typeof AdminConcoursRoute
  '/admin/disponibilites': typeof AdminDisponibilitesRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/fournisseurs': typeof AdminFournisseursRoute
  '/admin/offres': typeof AdminOffresRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/mon-compte/documents': typeof MonCompteDocumentsRoute
  '/mon-compte/paiements': typeof MonComptePaiementsRoute
  '/mon-compte/profil': typeof MonCompteProfilRoute
  '/mon-compte/reservations': typeof MonCompteReservationsRoute
  '/offres/$slug': typeof OffresSlugRoute
  '/reservation/$slug': typeof ReservationSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/mon-compte/': typeof MonCompteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activites-aquatiques': typeof ActivitesAquatiquesRoute
  '/activites-terrestres': typeof ActivitesTerrestresRoute
  '/bonnes-adresses': typeof BonnesAdressesRoute
  '/confirmation': typeof ConfirmationRoute
  '/logements': typeof LogementsRoute
  '/packs': typeof PacksRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/services-prives': typeof ServicesPrivesRoute
  '/vehicules': typeof VehiculesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/concours': typeof AdminConcoursRoute
  '/admin/disponibilites': typeof AdminDisponibilitesRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/fournisseurs': typeof AdminFournisseursRoute
  '/admin/offres': typeof AdminOffresRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/mon-compte/documents': typeof MonCompteDocumentsRoute
  '/mon-compte/paiements': typeof MonComptePaiementsRoute
  '/mon-compte/profil': typeof MonCompteProfilRoute
  '/mon-compte/reservations': typeof MonCompteReservationsRoute
  '/offres/$slug': typeof OffresSlugRoute
  '/reservation/$slug': typeof ReservationSlugRoute
  '/admin': typeof AdminIndexRoute
  '/mon-compte': typeof MonCompteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activites-aquatiques': typeof ActivitesAquatiquesRoute
  '/activites-terrestres': typeof ActivitesTerrestresRoute
  '/bonnes-adresses': typeof BonnesAdressesRoute
  '/confirmation': typeof ConfirmationRoute
  '/logements': typeof LogementsRoute
  '/packs': typeof PacksRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/services-prives': typeof ServicesPrivesRoute
  '/vehicules': typeof VehiculesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/concours': typeof AdminConcoursRoute
  '/admin/disponibilites': typeof AdminDisponibilitesRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/fournisseurs': typeof AdminFournisseursRoute
  '/admin/offres': typeof AdminOffresRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/mon-compte/documents': typeof MonCompteDocumentsRoute
  '/mon-compte/paiements': typeof MonComptePaiementsRoute
  '/mon-compte/profil': typeof MonCompteProfilRoute
  '/mon-compte/reservations': typeof MonCompteReservationsRoute
  '/offres/$slug': typeof OffresSlugRoute
  '/reservation/$slug': typeof ReservationSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/mon-compte/': typeof MonCompteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activites-aquatiques'
    | '/activites-terrestres'
    | '/bonnes-adresses'
    | '/confirmation'
    | '/logements'
    | '/packs'
    | '/paiement'
    | '/panier'
    | '/services-prives'
    | '/vehicules'
    | '/admin/clients'
    | '/admin/concours'
    | '/admin/disponibilites'
    | '/admin/documents'
    | '/admin/fournisseurs'
    | '/admin/offres'
    | '/admin/packs'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/reservations'
    | '/mon-compte/documents'
    | '/mon-compte/paiements'
    | '/mon-compte/profil'
    | '/mon-compte/reservations'
    | '/offres/$slug'
    | '/reservation/$slug'
    | '/admin/'
    | '/mon-compte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activites-aquatiques'
    | '/activites-terrestres'
    | '/bonnes-adresses'
    | '/confirmation'
    | '/logements'
    | '/packs'
    | '/paiement'
    | '/panier'
    | '/services-prives'
    | '/vehicules'
    | '/admin/clients'
    | '/admin/concours'
    | '/admin/disponibilites'
    | '/admin/documents'
    | '/admin/fournisseurs'
    | '/admin/offres'
    | '/admin/packs'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/reservations'
    | '/mon-compte/documents'
    | '/mon-compte/paiements'
    | '/mon-compte/profil'
    | '/mon-compte/reservations'
    | '/offres/$slug'
    | '/reservation/$slug'
    | '/admin'
    | '/mon-compte'
  id:
    | '__root__'
    | '/'
    | '/activites-aquatiques'
    | '/activites-terrestres'
    | '/bonnes-adresses'
    | '/confirmation'
    | '/logements'
    | '/packs'
    | '/paiement'
    | '/panier'
    | '/services-prives'
    | '/vehicules'
    | '/admin/clients'
    | '/admin/concours'
    | '/admin/disponibilites'
    | '/admin/documents'
    | '/admin/fournisseurs'
    | '/admin/offres'
    | '/admin/packs'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/reservations'
    | '/mon-compte/documents'
    | '/mon-compte/paiements'
    | '/mon-compte/profil'
    | '/mon-compte/reservations'
    | '/offres/$slug'
    | '/reservation/$slug'
    | '/admin/'
    | '/mon-compte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitesAquatiquesRoute: typeof ActivitesAquatiquesRoute
  ActivitesTerrestresRoute: typeof ActivitesTerrestresRoute
  BonnesAdressesRoute: typeof BonnesAdressesRoute
  ConfirmationRoute: typeof ConfirmationRoute
  LogementsRoute: typeof LogementsRoute
  PacksRoute: typeof PacksRoute
  PaiementRoute: typeof PaiementRoute
  PanierRoute: typeof PanierRoute
  ServicesPrivesRoute: typeof ServicesPrivesRoute
  VehiculesRoute: typeof VehiculesRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminConcoursRoute: typeof AdminConcoursRoute
  AdminDisponibilitesRoute: typeof AdminDisponibilitesRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminFournisseursRoute: typeof AdminFournisseursRoute
  AdminOffresRoute: typeof AdminOffresRoute
  AdminPacksRoute: typeof AdminPacksRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  MonCompteDocumentsRoute: typeof MonCompteDocumentsRoute
  MonComptePaiementsRoute: typeof MonComptePaiementsRoute
  MonCompteProfilRoute: typeof MonCompteProfilRoute
  MonCompteReservationsRoute: typeof MonCompteReservationsRoute
  OffresSlugRoute: typeof OffresSlugRoute
  ReservationSlugRoute: typeof ReservationSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MonCompteIndexRoute: typeof MonCompteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicules': {
      id: '/vehicules'
      path: '/vehicules'
      fullPath: '/vehicules'
      preLoaderRoute: typeof VehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services-prives': {
      id: '/services-prives'
      path: '/services-prives'
      fullPath: '/services-prives'
      preLoaderRoute: typeof ServicesPrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logements': {
      id: '/logements'
      path: '/logements'
      fullPath: '/logements'
      preLoaderRoute: typeof LogementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonnes-adresses': {
      id: '/bonnes-adresses'
      path: '/bonnes-adresses'
      fullPath: '/bonnes-adresses'
      preLoaderRoute: typeof BonnesAdressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites-terrestres': {
      id: '/activites-terrestres'
      path: '/activites-terrestres'
      fullPath: '/activites-terrestres'
      preLoaderRoute: typeof ActivitesTerrestresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites-aquatiques': {
      id: '/activites-aquatiques'
      path: '/activites-aquatiques'
      fullPath: '/activites-aquatiques'
      preLoaderRoute: typeof ActivitesAquatiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte/': {
      id: '/mon-compte/'
      path: '/mon-compte'
      fullPath: '/mon-compte/'
      preLoaderRoute: typeof MonCompteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/$slug': {
      id: '/reservation/$slug'
      path: '/reservation/$slug'
      fullPath: '/reservation/$slug'
      preLoaderRoute: typeof ReservationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/$slug': {
      id: '/offres/$slug'
      path: '/offres/$slug'
      fullPath: '/offres/$slug'
      preLoaderRoute: typeof OffresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte/reservations': {
      id: '/mon-compte/reservations'
      path: '/mon-compte/reservations'
      fullPath: '/mon-compte/reservations'
      preLoaderRoute: typeof MonCompteReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte/profil': {
      id: '/mon-compte/profil'
      path: '/mon-compte/profil'
      fullPath: '/mon-compte/profil'
      preLoaderRoute: typeof MonCompteProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte/paiements': {
      id: '/mon-compte/paiements'
      path: '/mon-compte/paiements'
      fullPath: '/mon-compte/paiements'
      preLoaderRoute: typeof MonComptePaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte/documents': {
      id: '/mon-compte/documents'
      path: '/mon-compte/documents'
      fullPath: '/mon-compte/documents'
      preLoaderRoute: typeof MonCompteDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/admin/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/admin/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/admin/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packs': {
      id: '/admin/packs'
      path: '/admin/packs'
      fullPath: '/admin/packs'
      preLoaderRoute: typeof AdminPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offres': {
      id: '/admin/offres'
      path: '/admin/offres'
      fullPath: '/admin/offres'
      preLoaderRoute: typeof AdminOffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fournisseurs': {
      id: '/admin/fournisseurs'
      path: '/admin/fournisseurs'
      fullPath: '/admin/fournisseurs'
      preLoaderRoute: typeof AdminFournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/disponibilites': {
      id: '/admin/disponibilites'
      path: '/admin/disponibilites'
      fullPath: '/admin/disponibilites'
      preLoaderRoute: typeof AdminDisponibilitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/concours': {
      id: '/admin/concours'
      path: '/admin/concours'
      fullPath: '/admin/concours'
      preLoaderRoute: typeof AdminConcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitesAquatiquesRoute: ActivitesAquatiquesRoute,
  ActivitesTerrestresRoute: ActivitesTerrestresRoute,
  BonnesAdressesRoute: BonnesAdressesRoute,
  ConfirmationRoute: ConfirmationRoute,
  LogementsRoute: LogementsRoute,
  PacksRoute: PacksRoute,
  PaiementRoute: PaiementRoute,
  PanierRoute: PanierRoute,
  ServicesPrivesRoute: ServicesPrivesRoute,
  VehiculesRoute: VehiculesRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminConcoursRoute: AdminConcoursRoute,
  AdminDisponibilitesRoute: AdminDisponibilitesRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminFournisseursRoute: AdminFournisseursRoute,
  AdminOffresRoute: AdminOffresRoute,
  AdminPacksRoute: AdminPacksRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  MonCompteDocumentsRoute: MonCompteDocumentsRoute,
  MonComptePaiementsRoute: MonComptePaiementsRoute,
  MonCompteProfilRoute: MonCompteProfilRoute,
  MonCompteReservationsRoute: MonCompteReservationsRoute,
  OffresSlugRoute: OffresSlugRoute,
  ReservationSlugRoute: ReservationSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  MonCompteIndexRoute: MonCompteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
